### ISSUE TITLE
Investigate intermittently failing spec

### ISSUE THREAD

**Issue by dylanwolff** [icelab/berg#31]
One particular spec relating to `Category` deletion is failing intermittently (output below). After restarting the build on TravisCI all specs pass. 

This is possibly related to the `DatabaseCleaner` config set in `spec/db_helper.rb`.

```
 1) Admin / Categories / Delete I can delete a category
     Failure/Error: click_link "Delete"
     
     Capybara::Poltergeist::ObsoleteNode:
       The element you are trying to interact with is either not part of the DOM, or is not currently visible on the page (perhaps display: none is set). It's possible the element has been replaced by another element and you meant to interact with the new element. If so you need to do a new 'find' in order to get a reference to the new element.
     # ./vendor/bundle/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/node.rb:21:in `rescue in command'
     # ./vendor/bundle/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/node.rb:17:in `command'
     # ./vendor/bundle/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/node.rb:34:in `find'
     # ./vendor/bundle/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/node.rb:38:in `find_xpath'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/node/base.rb:108:in `find_xpath'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/queries/selector_query.rb:112:in `block in resolve_for'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/node/base.rb:81:in `synchronize'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/queries/selector_query.rb:108:in `resolve_for'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/node/finders.rb:35:in `block in find'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/node/base.rb:85:in `synchronize'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/node/finders.rb:33:in `find'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/node/actions.rb:27:in `click_link'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:699:in `block (2 levels) in <class:Session>'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/admin/features/categories/delete_spec.rb:19:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:291:in `within'
     # ./vendor/bundle/ruby/2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
     # ./spec/admin/features/categories/delete_spec.rb:18:in `block (2 levels) in <top (required)>'
     # ./spec/db_helper.rb:21:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # ./vendor/bundle/ruby/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/base.rb:98:in `cleaning'
     # ./vendor/bundle/ruby/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ./vendor/bundle/ruby/2.3.0/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/db_helper.rb:20:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Capybara::Poltergeist::BrowserError:
     #   There was an error inside the PhantomJS portion of Poltergeist. If this is the error returned, and not the cause of a more detailed error response, this is probably a bug, so please report it. 
     #   
     #   Poltergeist.ObsoleteNode: 
     #   ./vendor/bundle/ruby/2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:351:in `command'
```

**Comment by dylanwolff** [comment]
Closing as this is no longer occurring.
